default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: souls_user
  password: nopassword
  pool: 5

development:
  <<: *default
  database: souls_development

test:
  <<: *default
  database: souls_test

production:
  <<: *default
  database: souls_production

